language: scala
sudo: false
scala:
  - 2.10.5
  - 2.11.6
jdk:
  - oraclejdk7
addons:
  postgresql: "9.3"
before_script:
  - psql -c "CREATE ROLE squeryl WITH SUPERUSER LOGIN PASSWORD 'squeryl';" -U postgres
  - psql -c "CREATE DATABASE squeryl;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO squeryl@"localhost"IDENTIFIED BY "squeryl";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE squeryl;" -usqueryl -psqueryl
  - cp org.squeryl.tests.cfg.travis org.squeryl.tests.cfg
script:
  - sbt ++${TRAVIS_SCALA_VERSION} test:compile
  - rm -r src/test/scala/org/squeryl/oracle/
  - rm -r src/test/scala/org/squeryl/mssql/
  - sbt ++${TRAVIS_SCALA_VERSION} test
