language: scala
sudo: false
scala:
- 2.10.6
- 2.11.11
matrix:
  include:
  - scala: 2.12.2
    jdk: oraclejdk8
  - scala: 2.13.0-M1
    jdk: oraclejdk8
  - dist: trusty
    group: edge
    sudo: required
    scala: 2.12.2
    jdk: oraclejdk9
    script:
    # https://github.com/sbt/sbt/pull/2951
    - git clone https://github.com/retronym/java9-rt-export
    - cd java9-rt-export/
    - git checkout 1019a2873d057dd7214f4135e84283695728395d
    - jdk_switcher use oraclejdk8
    - sbt package
    - jdk_switcher use oraclejdk9
    - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
    - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
    - cd ..
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/9ade5fa54914ca8aded44105bf4b9a60966f3ccd/sbt && chmod +x ./sbt
    - sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++${TRAVIS_SCALA_VERSION} test:compile
    - rm -r src/test/scala/org/squeryl/oracle/
    - rm -r src/test/scala/org/squeryl/mssql/
    - sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++${TRAVIS_SCALA_VERSION} test
jdk:
- oraclejdk7
addons:
  postgresql: '9.3'
before_script:
- psql -c "CREATE ROLE squeryl WITH SUPERUSER LOGIN PASSWORD 'squeryl';" -U postgres
- psql -c "CREATE DATABASE squeryl;" -U postgres
- mysql -e 'GRANT ALL ON *.* TO squeryl@"localhost"IDENTIFIED BY "squeryl";FLUSH PRIVILEGES;'
  -uroot
- mysql -e "CREATE DATABASE squeryl;" -usqueryl -psqueryl
- cp org.squeryl.tests.cfg.travis org.squeryl.tests.cfg
script:
- sbt ++${TRAVIS_SCALA_VERSION} test:compile
- rm -r src/test/scala/org/squeryl/oracle/
- rm -r src/test/scala/org/squeryl/mssql/
- sbt ++${TRAVIS_SCALA_VERSION} test
env:
  global:
  - secure: B/esoBi0gr3+/83hoVYfWrcQtOtVoBwI4qK7PjDeH89gV1tiyNUOp/E9+Lxt1RyJ4kQuiFaA241Toshy69f9AyUL4NCUo42noYEX7v66VppkAY3MfrCPKGAN9/urQF/ZELFiQblmAX3UzD91xluFzHjYpLcRDYe0vtYWN8EqJLw=
  - secure: BFWLPui/MHNHvWcpePTagUsHqnt3wqbJILgZuSFcKE0yPuydJzgoi5DNake/5rvGYKdyC6nCj6T8nShCNIXqOPSV5JL2gWaPbMrNxquXDy4CUy4zeAMHHrWO314ft2Xoa7zr6M+KeWpVAR/dEIIncjFNbhO3kDAgFPn4Vqm5z+w=
